### ISSUE TITLE
past due jobs in scheduled registry don't get picked up by --with-scheduler

### ISSUE THREAD

**Issue by gabriels1234** [rq/rq#1754] opened 2023-01-16 16:38 UTC
I have a Job that should have been enqueued an hour ago (it's in the scheduled registry).
I'm using the RQ embedded scheduler (--with-scheduler).
Is there anything to be done?

Thanks!

**Comment by lowercase00** [comment] 2023-01-18 05:04
@gabriels1234 do you have a minimal example that could be replicated?
If not, are the workers getting any new jobs? Does reseting the worker fixes it?
If you can try running both the queue and the worker from this commit 1fd6a032bf35f122a6b91c13e9734e6cb05f80ab, would be helpful to see the debug logs.

**Comment by walker2top** [comment] 2023-02-21 05:01
I am a new user of rq and encounter such similar problem though I am not sure if they are due to the same root cause

here's my codes

producer.py

```
from rq import Queue
from redis import Redis
from datetime import timedelta
from funclist import say_hello2
import time

queue = Queue(connection=Redis(host='127.0.0.1'))
job = queue.enqueue_in(time_delta=timedelta(seconds=10), func=say_hello2)

# check job status
while True:
    print(job.get_status())
    time.sleep(1)
```

worker.py
```
from rq import Worker
from redis import Redis

w = Worker(['default'], connection=Redis(host='127.0.0.1'))
w.work(with_scheduler=True)
```

not sure if there's something wrong with my codes but worker doesn't execute this job 10s after it's queued.
I start from using queue.enqueue(say_hello2) and that could work. then enqueue_at and enqueue_in could not work

hope that I can get help from masters here. thanks in advance!

**Comment by lowercase00** [comment] 2023-02-21 14:42
Hi @walker2top, welcome!

Are you running v1.13.0? Do you mind trying this exact same code with v1.12.0 please?
I don't think it's the same issue as above - but it may be something related to a change done in 1.13 on how the scheduler starts.

Thanks

**Comment by walker2top** [comment] 2023-02-22 17:24
hi @lowercase00 , my program is using rq v1.10.1 (I tried rq in a historic project)

Based on your suggestion, I make some tests for `v1.10.1`, `v1.12.0` and `v1.13.0`. Results are listed as following, and please note that all of 3 version have the same behaviors:

```
1. if I start rq worker via worker.py, "queue.enqueue" can make worker execute this job, but "queue.enqueue_in" can not;

2. if I start rq worker via cli with cmd "rq worker --with-scheduler", both "queue.enqueue" and "queue.enqueue_in" work
```

and there are also some other findings that I found in v1.12.0 and v1.13.0 ( I have tried v.1.10.1):

```
1. When jobs are executed by a worker, no matter they are from "queue.enqueue" or "queue.enqueue_in", no matter I start rq worker by cmd or python scripts, job status will be failed and finished in turns, which means if the current job fails, next one is bound to be finished (otherwise this worker restarts). when a rq worker starts/restarts, the first job is bound to be failed.

2. if I delete all items in redis and then start rq worker via cmd, it launches one worker (checked by logs and redis items); but if I delete all items in redis and then start rq worker via python scripts, it launches 2 workers(can see in logs, and redis) and only one of them are in the value of key "rq:worker". if I have started worker and stop it, which means redis has had related items, then next time I start worker via python script, there won't be 1 more worker launched.
```

they are all behavior in my environment. maybe you can try to reproduce it in your side as I have no idea whether they are due to package bugs or my codes.

thanks for your help. I will run rq worker via cli to temporarily solve this issue.

**Comment by lowercase00** [comment] 2023-02-23 01:22
@walker2top just to keep the information you gathered so far:

1. When using `queue.enqueue_in(...)` and starting the worker programmatically (`w.work(...)`) jobs don't get picked up by the worker;
2. When running through the cli with `rq worker ...` things seems to work normally;

So here there seems to be something different between the `cli` and the `work()` method, specifically when using the scheduler with `enqueue_at` and `enqueue_in`.

Now can you clarify the other two points, please?

- In any given scenario you're seeing jobs being marked as `failed`? Any additional information to this? Are you using dependencies? Is the worker restarting without any intervention? When restarting a worker the first job it picks up always fails?
- Starting from a clean redis database (`redis-cli FLUSHDB`) and starting the worker programmatically (`w.work(...)`) you're seeing two workers in the logs, but only one worker in Redis, is that it? If you start a worker, and stop it, when you start it again then everything works as expected?

I'm trying to separate potential issues to help us identity what might be causing this weird behavior.
Thanks for investigating this, really helpful.

**Comment by walker2top** [comment] 2023-02-23 14:02
hi @lowercase00 I have been confused by the behavior I observed just now but let me update it here firstly.

1. yesterday I did be able to reproduce the issue that jobs are failed and finished in turns every time(I tried more than 20 times and that's why I know they are in turns and restarting workers will reset it). 

regarding intervention:

- I have some other Pycharm window opened with other project but they are not running programs but none of them were running programs background. 
- the full code of enqueue job and start worker have been pasted before and the other file only contain a function to say hello by print() without import any package.
- And when a job failed, there were no new logs printed by worker(if it was error of import path, worker would print logs, but actually no logs in these cases)
- when worker is running programmatically, I restart it with pycharm's restart button or (stop + run)buttons. when it's running by cli, I just press control C to stop it and then execute cmd again. 

yes the first job always failed after a worker started yesterday.

I tried to reproduce it to check more detail but sry I can not reproduce it now. the first time I tried to reproduce it just now I run worker with cli through cmd and use enqueue_in to enqueue a job but it's strange that it's not executed, which didn't happened yesterday.
I clean all items in redis and tried again, but I don't see failed job any more. all are finished. but several time later a job enqueued by enqueued in can't be executed again( worker is running through cli as well). after I restart worker, worker immediately execute serveral jobs after it starts and then I don't encounter any other problem.

2. I see 2 workers shown in logs. and in redis, there are 2 new items with key "rq:worker:xxx" but only 1 of them is in value of item with key "rq:workers" or "rq:workers:default" (so it means only 1 worker is running?). then if I stop it and start it again, only 1 new item with "rq:worker:xxx" is appended in redis.

3. ohhh, it did works if I run work() with a __name__ == '__main__' block. this worker can handle jobs added by enqueue_in. quite surprising. and another new finding is that if I run worker in this way and stop it and then reverted the change to run worker without this block, there are also 2 workers shown in logs just like I start worker after clean redis.

above are all I can  see today and I am now totally confused... but sry I am not able to analyze them further due to my low programming skill level.


if you are interested in any other case, can let me know the steps and I will help to verify it in my side.

**Comment by lowercase00** [comment] 2023-02-23 14:15
The `scheduler` runs in its own `Process`. When you start a process you need to use `if __name__ == '__main__'` so that it only runs the main block once (otherwise the `Process` will import the module and run it again - this would even through a `RuntimeError` on Windows). So this is the issue when running the worker programmatically.

When running through the cli, and using features that relate to scheduling (`enqueue_at` for example), you need to run from the cli with `rq worker --with-scheduler`.

My suggestion is: make sure you're always using the `if __name__...` block when running the worker with `work(with_scheduler=True)` - if you don't have the scheduler that's not necessary. We should update the docs to make this clear.

For further troubleshooting I would try to avoid that many variables (programatic vs cli, scheduler vs non scheduler, enqueue_in vs enqueue_at etc) - this adds complexity and makes it harder to spot issues. Try to isolate things as much as possible in a way that we can reproduce.

Let us know if you have any other doubts.

**Comment by walker2top** [comment] 2023-02-23 14:38
yes i did test with conditions （programatic， cli）* （enqueue，enqueue_in）. I tried enqueue and enqueue_in every time I run a worker today and yesterday， but for same case I still got different results today. I guess it's also possible that remaining scheduled jobs（those not executed by worker that starts programatic without main block） may affect the behavior of next run.

thanks for your help. I will key an eye on it next time I use it

**Comment by lowercase00** [comment] 2023-02-23 14:41
Closing this one for now, the original issue by @gabriels1234 is stale.
If there are any other issues here feel free to reopen this, or open a new issue.

**Closed by lowercase00** 2023-02-23 14:41 UTC

**Comment by gabriels1234** [comment] 2023-02-23 15:01
@lowercase00 Thanks, I haven't faced this issue anymore, but also I added a self rescheduling job that guards all scheduled jobs, stale and not. (works with django-rq-scheduler's 2023.2.1+ that removed rq-scheduler in favor of the scheduler)
