### ISSUE TITLE
ScheduledJobRegistry wont run jobs with times in the past

### ISSUE THREAD

**Issue by Cody-Coleman** [rq/rq#1445] opened 2021-04-09 05:01 UTC
Trying to use the scheduled jobs registry to enqueue a job with a random time between 0 and 60 seconds. When the job gets picked up it checks some additional data if it should run and if there already is a task running it will re-queue itself with a random timer. 

Submitting 100s of jobs this way works pretty well but I get about 30 that all show up in the registry.get_expired_job_ids() and have execution times in the past. 

Shouldn't the worker be able to pick these jobs up as well? Is the queue getting overwhelmed and if it misses a job it cannot recover? 

I'm also unable to find a way to grab the job and re-queue it as all I can seem to get from the registry is a string of the job name, but not the actual job object in order to just kick it back on the scheduled queue. 

Here's some code bits: 

My worker: 
```python
    def start_worker(self, queue_name="main"):
        queue = Queue(queue_name, connection=Redis(self.redis_server, self.port))
        migration_worker = Worker(queue_name, connection=queue.connection, name="sequencer")
        migration_worker.work(with_scheduler=True, burst=True, logging_level="WARNING")
```

And the logic that if hit will enqueue the job again: 
```python
    if re_submit_vm:
        sequence = Queue("main", connection=Redis(config["redis_server"], config["redis_port"]))
        args = [vm_name, queue, sleep, destination, over_subscribe, maint_reason, autoconverge, requeue, role_isolation]
        sequence.enqueue_in(
            timedelta(seconds=random.randint(1, 60)),
            execute_vm_migrate,
            args=args,
            job_id=f"{vm_name}_{queue}_transport_sequence",
        )
```

Is it possible there are TTLS that need to be set for how long a job can be expired and still be picked up? Or does there need to be more workers to process the scheduled registry? 

And even if this is just a thing that happens, having some way to get the job to re-schedule it would be handy but the registry just seems to show the job_id strings, and the Job.fetchall can't fetch the job by that same string.

**Comment by Cody-Coleman** [comment] 2021-04-09 16:01
Just some additional info. When I pick one of these jobs in the `registry.get_jobs_to_schedule()` list and try to retrieve it, I get: 
```python
job = Job.fetch(expired_jobs[0], connection=r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scotty/.local/lib/python3.9/site-packages/rq/job.py", line 307, in fetch
    job.refresh()
  File "/home/scotty/.local/lib/python3.9/site-packages/rq/job.py", line 537, in refresh
    raise NoSuchJobError('No such job: {0}'.format(self.key))
rq.exceptions.NoSuchJobError: No such job: b'rq:job:atlas3-app.g1-iad.qops.net_migration_0_transport_sequence'
```
So are these scheduled jobs failing because the job object is never getting created?

**Comment by Cody-Coleman** [comment] 2021-04-14 15:16
We've seen where we have say 20 or so jobs in the scheduled registry with times to run sometime in the future, and another job will get picked up that takes a while to run (say 5 or 6 minutes) and during that time if any jobs had execution times that will have expired while the worker was working on that long job, they never get picked up again and we have to clear them out completely. So it really seems like once a job's scheduled execution time is to far in the past it can't get picked backup and ran. Would this get solved by running multiple workers against the scheduled queue?

**Comment by selwin** [comment] 2021-04-20 00:44
Looking at your code, it seems like you're reusing `job_id` which should be unique. Try fixing this line here and see what happens `job_id=f"{vm_name}_{queue}_transport_sequence".

**Comment by selwin** [comment] 2021-05-15 13:00
Closed as this is not a bug. Job ID should always be unique so that RQ can properly keep track of job execution times.

**Closed by selwin** 2021-05-15 13:00 UTC
