### ISSUE TITLE
:django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet" if rqworker name is the same as queue name

### ISSUE THREAD

**Issue by and-sm** [rq/rq#1180] opened 2020-01-18 23:49 UTC
I've tried django-rq, but it can't run worker with custom rq queue name, which is not present in Django settings.py. With rq it is possible. But found unhandled exception.

Env: django 2.2.9, rq 1.2.0.

Steps:
 - rqworker was launched in code as `proc = subprocess.Popen([executable + "/rqworker", str(uuid), "--burst", "--name=\"" + uuid + "\""]`
 - Queue configured in code as `Queue(name=uuid, connection=self.redis, is_async=True)`

Error:

```python 01:30:55: Worker rq:worker:"74fa4d0a-0960-40bd-8380-5b9bd01f786e": started, version 1.2.0
01:30:55: *** Listening on 74fa4d0a-0960-40bd-8380-5b9bd01f786e...
01:30:55: Cleaning registries for queue: 74fa4d0a-0960-40bd-8380-5b9bd01f786e
01:30:55: 74fa4d0a-0960-40bd-8380-5b9bd01f786e: start_run({'test':'1'}) (28c187b4-11b2-49b9-bf45-372035d6d824)
01:30:55: Worker rq:worker:"74fa4d0a-0960-40bd-8380-5b9bd01f786e": found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.7/site-packages/rq/job.py", line 54, in unpickle
    obj = loads(pickled_string)
  File "/home/user/software/loader/methods/my_loader.py", line 8, in <module>
    from loader.models import Model1, Model2, Model3, Model4
  File "/home/user/software/loader/models.py", line 7, in <module>
    class Environments(models.Model):
  File "/home/user/venv/lib/python3.7/site-packages/django/db/models/base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/user/venv/lib/python3.7/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/home/user/venv/lib/python3.7/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 515, in work
    self.execute_job(job, queue)
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 727, in execute_job
    self.fork_work_horse(job, queue)
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 667, in fork_work_horse
    self.main_work_horse(job, queue)
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 744, in main_work_horse
    raise e
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 741, in main_work_horse
    self.perform_job(job, queue)
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 866, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/home/user/venv/lib/python3.7/site-packages/rq/worker.py", line 785, in prepare_job_execution
    self.procline(msg.format(job.func_name, job.origin, time.time()))
  File "/home/user/venv/lib/python3.7/site-packages/rq/job.py", line 246, in func_name
    self._unpickle_data()
  File "/home/user/venv/lib/python3.7/site-packages/rq/job.py", line 214, in _unpickle_data
    self._func_name, self._instance, self._args, self._kwargs = unpickle(self.data)
  File "/home/user/venv/lib/python3.7/site-packages/rq/job.py", line 56, in unpickle
    raise UnpickleError('Could not unpickle', pickled_string, e)
rq.exceptions.UnpickleError: ('Could not unpickle', AppRegistryNotReady("Apps aren't loaded yet."))
`

**Comment by selwin** [comment] 2020-01-25 01:37
The error `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.` means that your worker tried to access certain Django dependent objects without properly setting up your Django environment. You can look at django-rq's source code and see how it setup Django before running the workers.

I'm closing this issue as this is not a bug.

**Closed by selwin** 2020-01-25 01:37 UTC
