### ISSUE TITLE
Scheduler does not support retry?

### ISSUE THREAD

**Issue by vaal-** [rq/rq#1338] opened 2020-09-18 14:14 UTC
Is there any reason for this?
https://github.com/rq/rq/blob/master/rq/queue.py#L429-L430
Here the parameter retry is not passed further.

I did a couple of tests on code where I added a parameter passing. Everything worked out fine. But maybe there are some pitfalls?

**Comment by nerok** [comment] 2020-09-21 12:52
I would assume that the issue is that no one has noticed when adding the retry functionality, same was the issue with the job-decorator (see #1319 for that fix). I would assume you could make a pull request if that is a feature you need.

**Comment by selwin** [comment] 2020-09-28 08:45
Yeah, PR for this is welcome.

**Comment by johnraz** [comment] 2020-10-29 10:32
@selwin I believe this can be closed :-)

**Comment by selwin** [comment] 2020-10-29 13:35
Fixed in https://github.com/rq/rq/pull/1343

**Closed** 2020-10-29 13:37 UTC
