### ISSUE TITLE
ValueError exception in register_birth()

### ISSUE THREAD

**Issue by DavidHwu** [rq/rq#497] opened 2015-03-03 00:41 UTC
May I suggest that we provide a exception class detail to reflect this existing ValueError?
There are 2 possible ValueErrors in Worker class, and this variant is recoverable.
It would be great to have a specific Exception class to reflect this scenario, and let the caller intercept and deal with it should it be encountered.

def register_birth(self):
        ...
            raise ValueError('There exists an active worker named \'%s\' '
                             'already.' % (self.name,))

**Comment by selwin** [comment] 2015-11-08 12:04
I think the use case you described is a little bit of an edge case so I'd prefer to keep it as it is right now. For your use case, you can always inspect the exception message to catch this particular exception.

**Comment by stratosgear** [comment] 2017-11-13 15:02
Hi, recently also got faced with this.  I get:

```
11/13/2017 3:47:16 PMTraceback (most recent call last):
11/13/2017 3:47:16 PM  File "/backend/large_jobs_listener.py", line 38, in <module>
11/13/2017 3:47:16 PM    w.work()
11/13/2017 3:47:16 PM  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 446, in work
11/13/2017 3:47:16 PM    self.register_birth()
11/13/2017 3:47:16 PM  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 259, in register_birth
11/13/2017 3:47:16 PM    raise ValueError(msg.format(self.name))
11/13/2017 3:47:16 PMValueError: There exists an active worker named u'd2034c84bb5b.13' already
11/13/2017 3:47:17 PM2017/11/13 14:47:17 Command exited with error: exit status 1
```

I wouldn't mind catching the exception and inspecting the message, but what is the right procedure to recover?

 I see that this exception is throw here:

https://github.com/nvie/rq/blob/e5de3dfbb55e444e438f49dd0a4d1328e56213ee/rq/worker.py#L259
but I do not understand the circumstances it is thrown. I would appreciate some hints on how to recover.

Thanks.

**Comment by stratosgear** [comment] 2017-11-13 15:16
It seems it depends on the `self.key` which depends on the `self.name` which in my case, since I'm not providing any worker names, they are derived automatically from the hostname (the worker is run from inside a Docker container)

I could either generate a random worker name (which I think is stupid) or try to delete the Redis hash key that confuses RQ at:

https://github.com/nvie/rq/blob/e5de3dfbb55e444e438f49dd0a4d1328e56213ee/rq/worker.py#L258

Do you think that, if I manually delete that Redis key and restart the worker, will this create any weird side effects?

**Comment by nicbou** [comment] 2018-01-28 20:22
I'm having the same issue, but this thread hasn't been answered in a few months. Did anyone find a solution?

**Comment by bitfinity** [comment] 2018-04-05 07:29
Yep same issue

**Comment by selwin** [comment] 2018-04-05 10:50
Let's create a `DuplicateName` exception for now. Could someone please open a PR for this?

**Comment by mrgordon** [comment] 2018-09-06 18:28
This continues to be an annoying issue. It greatly impedes the ability to use this project

**Comment by selwin** [comment] 2018-09-06 23:10
I'm closing this as a duplicate of https://github.com/rq/django-rq/issues/296#issuecomment-419195218 . This thread has a genuine use case that explains how the issue can be easily reproduced, I also proposed a fix for this issue.

**Closed by selwin** 2018-09-06 23:10 UTC

**Comment by horida** [comment] 2018-12-10 14:04
@selwin sorry, but can you point me to the part of the code where this is fixed? In the django-rq issue you proposed the use of a UUID but I can't find the solution though both issues are marked as solved.
Thanks
