### ISSUE TITLE
Jobs wrongly moved to failed registry (stuck in intermediate queue)

### ISSUE THREAD

**Issue by antmatyjajo** [rq/rq#2061] opened 2024-03-19 17:39 UTC
Hi,

I am running a large-ish number of short (<10s) jobs, and I noticed that some of them were failing... But, looking at the worker logs for the failed jobs, and then inspecting the jobs, the results were fine, "Job OK" from the worker, etc. Indeed, the "failed" jobs were simultaneously in the finished and failed registries, so I thought it may be related to #1507, but I think not.

Basically what seems to be happening is the job is first put in the failed registry, meanwhile, it carries on running quite happily and eventually somewhat later outputs a result and is marked as successfully finished. 

The problem is that because all these jobs are happening inside another job that is periodically processing a batch of incoming results, once the batch is completed, I am polling the job status for all jobs in the batch. So, when some jobs are marked as failed, even though they later succeed, I only receive the failure because that's the first "finish" comes up while polling.

It seems the issue is happening during `clean_intermediate_queue()`, every 10 minutes; changing the default maintenance interval to something lower makes it easier to reproduce the issue.

Monitoring the failed registry in `rq-dashboard` also shows the behaviour - a job will appear when it "fails", with a status message of 'Job was stuck in intermediate queue.', but then on the next dashboard update that status message is gone, and the same job has also appeared in the finished registry.

I have made a (somewhat) minimal example:

```python
# test_rq.py
from rq import Queue
from redis import Redis
import random
import time
from datetime import datetime
from multiprocessing import Pool

conn = Redis("here.is.the.redis.server")

def submit_task(index):
    print(f"submit sub task {index}")
    q = Queue("sub_q", connection=conn)
    sub_job = q.enqueue("test_rq.task")
    # await some result
    while True:
        res_status = sub_job.get_status(refresh=True)
        if res_status in ["finished", "stopped", "canceled", "failed"]:
            print(f"{datetime.now()} Sub job done with status {res_status.upper()}")
            if res_status == "finished":
                # Only here to not pollute the finished queue; it does clean some "failed" jobs as well due to timing I guess
                sub_job.delete()
            break
        time.sleep(0.1)
    # Normally would do some other work with the result

def task():
    # Simulate some work
    print(f"{datetime.now()} begin sub task")
    time.sleep(random.uniform(4,7))
    print(f"{datetime.now()} done sub task")

if __name__ == "__main__":
    print(f"{datetime.now()} begin all")
    with Pool(40) as pool:
        # Normally would run some number of iterations/batches here rather than one big group...
        pool.map(submit_task, range(100000))
```

Running that with some decent number of workers (`for i in $(seq 1 40); do rq worker sub_q & done`), and setting default maintenance interval to something manageable seems to reproduce the problem reliably.

Is this a bug? Or am I doing something wrong...?

(Also, any tips on the polling results part appreciated, no idea what is best practice there...)

Thanks!

**Comment by 1F357** [comment] 2024-03-28 16:22
I'm having the same problem, it seems to be more likely to occur when I'm inserting a small number of tasks, and the problem becomes rare when I'm inserting a large number of tasks at once.
I found this very strange. This problem seriously affected the operation of my program and I had to write a separate detection program to deal with it.

**Comment by selwin** [comment] 2024-04-13 07:56
> I am running a large-ish number of short (<10s) jobs, and I noticed that some of them were failing... But, looking at the worker logs for the failed jobs, and then inspecting the jobs, the results were fine, "Job OK" from the worker, etc. Indeed, the "failed" jobs were simultaneously in the finished and failed registries, so I thought it may be related to https://github.com/rq/rq/issues/1507, but I think not.

> Basically what seems to be happening is the job is first put in the failed registry, meanwhile, it carries on running quite happily and eventually somewhat later outputs a result and is marked as successfully finished.

I checked RQ's source code and found no indication that a job in the `FailedJobRegistry` can be moved to `FinishedJobRegistry` without going through the retry mechanism. My advice would be to check whether there's something in your code that manually changes RQ's job status.

I'm closing this issue unless you have something more concrete I can look at (a failing test case would be great).

**Comment by 1F357** [comment] 2024-04-13 13:21
> > I am running a large-ish number of short (<10s) jobs, and I noticed that some of them were failing... But, looking at the worker logs for the failed jobs, and then inspecting the jobs, the results were fine, "Job OK" from the worker, etc. Indeed, the "failed" jobs were simultaneously in the finished and failed registries, so I thought it may be related to #1507, but I think not.
> 
> > Basically what seems to be happening is the job is first put in the failed registry, meanwhile, it carries on running quite happily and eventually somewhat later outputs a result and is marked as successfully finished.
> 
> I checked RQ's source code and found no indication that a job in the `FailedJobRegistry` can be moved to `FinishedJobRegistry` without going through the retry mechanism. My advice would be to check whether there's something in your code that manually changes RQ's job status.
> 
> I'm closing this issue unless you have something more concrete I can look at (a failing test case would be great).

Thanks for your reply

emm, from my limited observation, **in my case**, I looked at the logs of the various workers, and when the `job was stuck in intermediate queue` issue was triggered, no worker indicated that they had received the job, and the job was not processed by any of them - I'm pretty sure of that. The task was not processed by any of the workers - as the first step of each of my jobs was to request an api, which did not receive any requests.

The `job was stuck in intermediate queue issue`  I'm experiencing is more likely to be triggered when my workers are much larger than the number of jobs I'm adding at once (e.g. I have 50 worker servers, and I'm inserting 3 jobs).

My workers are spread across many servers around the world, and the **latency of these worker servers connecting to the rq redis server varies**. I suspect that the `job was stuck in intermediate queue` issue is caused when different workers(each of them has different latency) are grabbing a same task.

It goes something like this: I insert some jobs, the jobs doesn't show up in any of the success/failure/processing/queued queues, it just disappears, and then after a while the jobs show up together in the failure queue( with error `job was stuck in intermediate queue`).

When I reduced the number of my worker servers, this problem was significantly alleviated.

RQ is really a great program, but, due to my time constraints I didn't look into the problems I was having in detail, and I was forced to switch to Celery, which is working fine so far (by the way, the Celery's docs are not nearly as easy to read and logical as rq's).

**Comment by antmatyjajo** [comment] 2024-04-16 09:39
Hi @selwin many thanks for following up on this.

> I'm closing this issue unless you have something more concrete I can look at (a failing test case would be great).

The issue can be reproduced with the code I originally posted. I have simplified it a bit to remove any randomness, no deletion of jobs, and to try to make it as minimal as possible:

```python
# test_rq.py
from rq import Queue
from redis import Redis
import time
from datetime import datetime
from multiprocessing import Pool

conn = Redis("localhost")

def submit_task(index):
    print(f"submit sub task {index}")
    q = Queue("sub_q", connection=conn)
    sub_job = q.enqueue("test_rq.task")
    # await some result
    while True:
        res_status = sub_job.get_status(refresh=True)
        if res_status in ["finished", "stopped", "canceled", "failed"]:
            print(f"{datetime.now()} Sub job done with status {res_status.upper()}")
            break
        time.sleep(0.1)

def task():
    # Simulate some work
    print(f"{datetime.now()} begin sub task")
    time.sleep(10)
    print(f"{datetime.now()} done sub task")

if __name__ == "__main__":
    with Pool(10) as pool:
        pool.map(submit_task, range(100000))
```

Multiprocessing is only there so that many jobs can be submitted and monitored simultaneously. The problem can also be reproduced with e.g., `ThreadPoolExecutor`.

The sleep interval does not seem to make much difference; I tried with short tasks (1 second) and 10 seconds as per here, and in either case I get the same problem.

To reproduce the issue I start up a group of workers - `for i in $(seq 1 4); do rq worker --maintenance-interval 15 sub_q & done` - and then separately run `python test_rq.py`. 

More workers possibly increases the probability of observing the problem. I was originally running with 40 workers.

I have lowered the maintenance interval to make it easier to observe the problem; when I originally noticed the problem, I was running all workers with just the default maintenance interval of 10 minutes.

I have tried this on a linux server and a macos laptop. In both cases I can reproduce the problem, whether running redis locally, or connecting to a remote redis instance.

> My advice would be to check whether there's something in your code that manually changes RQ's job status.

Thank you. The real production code does more but in theory, other than retrieving the job result, the only real interaction with rq is as per the script above; apart from submission and setting/updating job meta everything else is read only (retrieving results, meta, status, ...). 

At no point do I manually change the status - in any case the minimal script above reliably reproduces the problem for me.

At the first, and subsequent, maintenance interval(s) jobs may appear in the failed registry with 'Job was stuck in intermediate queue.'. Shortly after, they will also be in the successfully finished job registry. The same job ID is present in both registries.

I hope this is minimal enough; if there's something else I can provide please let me know.

**Comment by selwin** [comment] 2024-04-16 11:51
Thanks, I’ll take a look when I have the time. Reopening the issue for now.

**Comment by nrlulz** [comment] 2024-04-25 22:26
I am pretty sure this is happening to us too. I haven't been able to reproduce it in isolation, but I did do some digging into logs and RQ code. I don't know if this will help at all, but here's what I found.

Scheduler (not rq scheduler but our own process that just queues a job) logs:
```
[2024-04-10 17:05:17,922] INFO:     core.management.commands.scheduler - queued job: Job('job-id-here', enqueued_at=datetime.datetime(2024, 4, 10, 17, 5, 17, 921910))
```

RQ Worker A logs:
```
[2024-04-10 17:05:18,041] DEBUG:    rq.worker - Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
[2024-04-10 17:05:18,041] DEBUG:    rq.worker - Dequeueing jobs on queues default and timeout 405
[2024-04-10 17:05:18,042] DEBUG:    rq.worker - Dequeued job job-id-here from default
[2024-04-10 17:05:18,042] INFO:     rq.worker - default: rq_run() (job-id-here)
[2024-04-10 17:05:18,043] DEBUG:    rq.worker - Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
[2024-04-10 17:05:18,154] DEBUG:    rq.worker - Started Job Registry set.
[2024-04-10 17:05:18,154] DEBUG:    rq.worker - Preparing for execution of Job ID job-id-here
[2024-04-10 17:05:18,154] DEBUG:    rq.worker - Sent heartbeat to prevent worker timeout. Next one should arrive in 90 seconds.
[2024-04-10 17:05:18,156] DEBUG:    rq.worker - Job preparation finished.
[2024-04-10 17:05:18,156] DEBUG:    rq.worker - Performing Job...
[2024-04-10 17:05:19,044] <logs from the job itself begin>
[2024-04-10 17:05:19,233] <logs from the job itself end>
[2024-04-10 17:05:19,241] DEBUG:    rq.worker - Finished performing Job ID job-id-here
[2024-04-10 17:05:19,242] DEBUG:    rq.worker - Handling successful execution of job job-id-here
[2024-04-10 17:05:19,242] DEBUG:    rq.worker - Saving job job-id-here's successful execution result
[2024-04-10 17:05:19,243] DEBUG:    rq.worker - Removing job job-id-here from StartedJobRegistry
[2024-04-10 17:05:19,243] DEBUG:    rq.worker - Finished handling successful execution of job job-id-here
[2024-04-10 17:05:19,243] INFO:     rq.worker - default: Job OK (job-id-here)
[2024-04-10 17:05:19,243] DEBUG:    rq.worker - Result: ''
[2024-04-10 17:05:19,243] INFO:     rq.worker - Result is kept for 86400 seconds
```

RQ Worker B logs:
```
[2024-04-10 17:05:18,069] INFO:     rq.worker - Cleaning registries for queue: default
[2024-04-10 17:05:18,075] DEBUG:    rq.worker - Handling failed execution of job job-id-here
```

My interpretation of the above (please correct me if I misunderstood anything!):
1. 17:05:17,922 job is queued
1. 17:05:18,042 worker A dequeues job
    * this moves the job from the default queue to the intermediate queue
1. 17:05:18,069 worker B cleans registries
    * this checks (among other things) for jobs that are in the intermediate queue but not in the started registry, these are [assumed to have failed](https://github.com/rq/rq/blob/master/rq/maintenance.py#L18)
1. 17:05:18,075 worker B marks the job as failed with reason "Job was stuck in intermediate queue"
1. 17:05:18,154 worker A prepares to run job
    * this sends a job heartbeat, which adds the job to the started registry
    * this also removes the job from the intermediate queue
1. 17:05:18,156 worker A begins the actual work
1. 17:05:19,241 worker A completes the actual work
1. 17:05:19,242 worker A marks the job as successful

My hypothesis is that there is a short time (in this example, from :18.042 to :18.154) during which a job waiting in the intermediate queue will meet that criteria for being considered "stuck," and if another worker happens to do the clean registries process right then, it will record that failure result, even though (as @antmatyjajo said), Worker A, which had already dequeued the job, happily continues executing it and then records a successful result.

**Comment by selwin** [comment] 2024-04-25 23:38
@nrlulz thanks, what you said makes sense. Will write a patch for it.

**Comment by selwin** [comment] 2024-05-01 07:14
Fixed in https://github.com/rq/rq/commit/e2d144d7727b5efac34389e8b054969b4ea76271

**Closed by selwin** 2024-05-01 07:14 UTC
