### ISSUE TITLE
Job is pick up by two worker

### ISSUE THREAD

**Issue by KePeng1019** [rq/rq#1854] opened 2023-03-06 02:04 UTC
In my worker logs, I found one job(the job id is same) is pick up by two worker at same time, this is a serious issue for use. Can you help? I run 8 workers in ec2 and k8s docker container.
Also, how the job is generated? If I call enqueue with same function and params, will the job id generated by the same?

**Comment by lowercase00** [comment] 2023-03-06 06:11
@KePeng1019 do you manually create two jobs with the same id?

The job ID can be either manually passed, or if it's not, it will automatically generate a `str(uuir4())`, so no, the automatically generated job id will never be the same.

There are some issues related to duplicate job ids here #1701 and #1826 and also #1521, did you check those to see if you're problem might be related? There are other issues with this topic as well if I remember correctly.

**Comment by KePeng1019** [comment] 2023-03-06 06:39
> @KePeng1019 do you manually create two jobs with the same id?
> 
> The job ID can be either manually passed, or if it's not, it will automatically generate a `str(uuir4())`, so no, the automatically generated job id will never be the same.
> 
> There are some issues related to duplicate job ids here #1701 and #1826 and also #1521, did you check those to see if you're problem might be related? There are other issues with this topic as well if I remember correctly.

Thanks, these issue are not related. I do not manual set job id, so this should be a job pick up by two worker at the same time,  this issue  [1831](https://github.com/rq/rq/issues/1831) seems similar to my issue, but I do not found any solution for this.

**Comment by lowercase00** [comment] 2023-03-06 07:06
Do you have more information please? It's very hard to try to understand what's going on without any kind of info.

Are you running one worker per container? How are you enqueueing the job (just `enqueue()` or `_at`)? With or without scheduler? Do you notice any sort of pattern when this happens? Do you have an example to replicate the issue? Did you check whether you had 1 or 2 jobs saved in Redis?

**Comment by KePeng1019** [comment] 2023-03-07 01:01
> Do you have more information please? It's very hard to try to understand what's going on without any kind of info.
> 
> Are you running one worker per container? How are you enqueueing the job (just `enqueue()` or `_at`)? With or without scheduler? Do you notice any sort of pattern when this happens? Do you have an example to replicate the issue? Did you check whether you had 1 or 2 jobs saved in Redis?

I run one worker in per container and start by command ```python3 manage.py rqworker high default low --with-scheduler```.
The job is was run by ```
            queue = django_rq.get_queue()
            queue.enqueue_in(timedelta(seconds=delay_seconds, func, params)
```
This happens on two worker one deployed on ec2 and another on k8s platform.
I found the job was pick up by two worker in logs,  I can not  replicate this issue and have not check the Redis.
This issue is reported by [#1831](https://github.com/rq/rq/issues/1831) last two weeks.

**Comment by lowercase00** [comment] 2023-03-07 02:48
@KePeng1019 thanks for the details. #1831 had a few other aspects to it (decorator, supervisord, multiple workers single environment, django_rq) and not much detail, so a lot of things going at the same time. In a scenario where we can't replicate an issue, tends to help to try to reduce the number of variables in the problem.

I _think_ this looks like something related to the locking mechanism on the scheduler. When you do `enqueue_in` you are actually scheduling a task, and when you have multiple workers running, only a single scheduler should run (so that no two tasks get picked up by more than on scheduler) - for that to work the scheduler has a locking mechanism in which only a single scheduler acquired the lock at any given time. So perhaps the task is being saved on the registry twice, or perhaps two schedulers are enqueueing that particular task.

Can you please check the Redis key for the locking mechanism: `rq:scheduler-lock:%s` and also the `ScheduledJobRegistry`? Also, can you tell whether this happens with a specific number of workers, or a specific `delay_seconds` or even a specific function?

That all being said, just like #1831, it seems you are using `django-rq`. From what I can tell by quickly looking through `django-rq` codebase it should be a simple wrapper, so I wouldn't expect any different a behavior between the two projects, but I'm curious whether you would see this same issue with `rq` (without `django-rq`) - perhaps there's some conflicting logic here? I'm not particularly familiar with `django-rq`, maybe @selwin has some insights into the implementation.

**Comment by buroa** [comment] 2023-03-08 14:07
I am seeing this as well and it's pretty impactful as it's running steps twice. In the `queue.enqueue` function I set a `on_failure` handler which depending on the exception that was thrown, either resets the retries or sets them to 0 if it's a known "bad" exception.

When this exception is throw, I can see it in the logs, but the same worker that threw this exception retries *as well as* a new worker picks up this job. This results in two workers working on the same job.

It's random, but it does happen.

**Comment by lowercase00** [comment] 2023-03-08 17:46
@buroa does your retry logic uses the `retry_interval`?
Also, do you experience this same issue when you remove your failure callback, retry manipulation logic out of the equation?
How many workers are you running, and how are you running them?
I'm trying to narrow down the issue to a specific component, to try to replicate (and fix) this.

At last, as I mentioned in the last post:

> can you please check the Redis key for the locking mechanism: `rq:scheduler-lock:%s` and also the `ScheduledJobRegistry`? 

Wondering if there's something failing on the `lock` or if the job is being scheduled more then once - in one case the issue would be with the lock, on the other, would be on the scheduler sending registering tasks.

**Comment by selwin** [comment] 2023-03-08 23:14
@buroa can you try running this again with DEBUG level logging on RQ? So we can actually see what RQ does when handling exceptions and requeueing.

**Comment by gg718** [comment] 2023-06-04 21:21
I'm also experiencing this, very similar situation to what was described so I assume a similar root cause. Once a job has completed successfully for me, it seems to be being picked up by the workers and run again.

Some notes:
* Using rq v1.15.0
* I am running the worker programmatically, i.e. `Worker(...).work(with_scheduler=True)`
* Using `retry=Retry(...)` - in my case I am specifying `max=10` and `interval=600`
* Using `enqueue` to schedule the job
* Manually specifying `job_id`

**Comment by CodeWithOz** [comment] 2024-02-07 12:50
@gg718 did you get any more info? I've experienced what you described but I use `django-rq` in combination with `rq-scheduler`.

**Comment by sgorodskoi** [comment] 2024-02-27 15:51
I met same problem. The reason, I suppose, is that workers are running in docker containers and pid of every worker is 1, and rq thinks that this is the same worker.
Steps to reproduce: you need at least 3 workers inside containers (check - dashboard will be show only 1), create task, it will be taken by worker:1, then re-enqueue task inside working task - it will be taken by 2 workers in the same time - this is my scenario

**Comment by andy2mrqz** [comment] 2024-03-20 22:53
I also ran into this and, with the help of comments on this issue, had some findings that helped me narrow down when this happens/how to reproduce.

I run `rq worker --with-scheduler` on ECS, using supervisord to create 10 processes.  I also autoscale my ECS service, so occasionally I will have 10 separate containers with 10 separate processes.

As @sgorodskoi pointed out, there is `pid` collision across containers.  I was able to confirm that when a job_id was incorrectly picked up twice, it happened when there were multiple containers running with workers of the same `pid` (37 in my case).  This concept looks like `Container A: Worker A with pid 37`, `Container B: Worker A with pid 37`

It sounds like a long-term solution in `rq` would be to ensure that the lock is unique across containers, even when worker pids across containers can be the same.  But this would involve some thought/risk of breaking changes.  I am unfamiliar with `rq`'s internals so it would take me some time to come up with a proposal that would not cause side-effects (open to suggestions!).

If I come up with a short-term solution for developers using `rq` to avoid `pid` collision in the rq schedule lock across containers, I'll post back!

**Comment by selwin** [comment] 2024-03-20 23:59
> I run rq worker --with-scheduler on ECS, using supervisord to create 10 processes. I also autoscale my ECS service, so occasionally I will have 10 separate containers with 10 separate processes.

Ok, this gives me a little bit of clue about what may have happened. When ECS duplicate your containers, does the base container image already have workers with schedulers running? This may confuse RQ because each container already has a scheduler which thinks it has an exclusive lock and the state is duplicated.

The process of acquiring lock itself is done on Redis and should not matter even if workers across different machines have the same PID.

**Comment by andy2mrqz** [comment] 2024-03-21 06:12
@selwin thanks for your response.

> When ECS duplicate your containers, does the base container image already have workers with schedulers running?

Every ECS container is initiated exactly the same way, by running supervisord set to 10 processes.  The exact command supervisor runs for each of the 10 processes is `rq worker --with-scheduler --name=%(ENV_RQ_WORKER_PREFIX)s-%(process_num)s`, where `ENV_RQ_WORKER_PREFIX` is a unique identifier for the container that we set and `process_num` is 0-9.

So every process in a single container is run with the scheduler, and every container runs multiple rq workers with scheduler.

> This may confuse RQ because each container already has a scheduler which thinks it has an exclusive lock and the state is duplicated.

Got it.  All my containers submit jobs to the default queue, so in redis I see that the key for the lock is `rq:scheduler-lock:default` with a `pid` as the value (e.g. `37`).

> The process of acquiring lock itself is done on Redis and should not matter even if workers across different machines have the same PID.

I apologize but I'm not sure I follow - is there anything you would change in my setup to prevent rq from improperly running a job twice?  Or is this a change that would need to be addressed in rq?

**Comment by Molx32** [comment] 2024-09-07 00:51
Hi! I ran into the same issue and I might have a workaround, although I can't explain what happens (unfortunately I am a Redis/rq noob, not a developer).

### Context
I run a project in a total of 5 Docker containers deployed in the same virtual network named _common_, and bridged to my host. Two containers are rq workers. Here is a shorten version of my _docker-compose.yml_ file (I removed some info to make it shorter).
```
services:
    # Database
    database:
        image: postgres
        networks:
            - common

    # Redis server (queue)
    redisserver:
        image: redis:latest
        ports:
            - 6379:6379
        command: redis-server --loglevel debug
        networks:
            - common

    # Redis workers
    fetcher_worker:
        image: smsexplorer:latest
        depends_on:
            - redisserver
            - database
        command: rq worker --name fetcher --url redis://redisserver:6379
        networks:
            - common
    
    data_worker:
        image: smsexplorer:latest
        depends_on:
            - fetcher_worker
            - database
        command: rq worker --name data --url redis://redisserver:6379
        networks:
            - common

    # Web server
    smsexplorer:
        image: smsexplorer:latest
        depends_on:
            - redisserver
            - database
        build: .
        restart: on-failure
        ports:
            - 80:9000
        volumes:
            - exports:/etc/data/exports
            - imports:/etc/data/imports
        networks:
            - common

networks:
    common:
        driver: bridge
```

The SMSExplorer image is build from my sources and runs a Flask server. Before serving web pages, the Flask server initializes some stuff by running a job with the following line. You may notice an unusual `job_timeout` set to `-1` so that my job runs indefinitely, but it has no impact on the current issue and works fine.
`q.enqueue(TargetInterface.create_instance_receivesmss, job_id=Config.REDIS_JOB_ID_FETCHER, job_timeout=-1)`

### What makes a difference (workaround)
Now, Flask recommends to run behind a _Web Server Gateway Interface (WSGI)_ rather than running Python directly. When I started my project, I chose one of the most used and documented which is [uWSGI](https://uwsgi-docs.readthedocs.io/en/latest/). In other words, my Flask server run with the following command in Dockerfile : `CMD [ "uwsgi", "--ini", "uwsgi.ini"]`. **By running this, my job is picked up only once, as expected.**

Recently, I noticed that uWSGI prevents me to fetch _rq_ jobs (I don't know why, I'm still working on it). So I disabled uWSGI by modifying my Dockerfile to `CMD [ "python3", "SMSExplorer.py"]`. **This introduces the bug, and causes my job to get executed by my two workers, at the same time.**

### Reproduction steps
I have a public repo for my project you can fetch and hopefully set up easily to reproduce the issue : [this commit](https://github.com/Molx32/SMSExplorer/tree/380a1c382f9733e4ac1ee337b99ec536a8935046) doesn't use uWSGI and implements the bug.

**Comment by selwin** [comment] 2024-09-07 01:39
@Molx32 the issue is not that two RQ workers pickup the same job, but rather that your script pushes two jobs using the same `job_id`. https://github.com/Molx32/SMSExplorer/blob/380a1c382f9733e4ac1ee337b99ec536a8935046/SMSExplorer.py#L48

This explains why running your script differently triggers this bug. The bug is not in RQ itself, but rather the code that pushes the job into RQ.

I'm closing this thread :)

**Closed by selwin** 2024-09-07 01:39 UTC
Labels: bug

**Comment by coredumperror** [comment] 2025-05-08 00:54
@andy2mrqz Did you ever solve your issue with multiple RQ workers picking up the same scheduled job when they had the same PID on different containers?
