### ISSUE TITLE
Python worker(with scheduler) script is starting with a RuntimeError and an unpredictable delay.

### ISSUE THREAD

**Issue by fehimaltinisik** [rq/rq#1652] opened 2022-05-03 14:19 UTC
Hi Folks!

I am trying to implement a custom Python script utilizing a _worker with scheduler_. The below _scheduler.py_ script:

- Processes the consecutive jobs posted by _.enqueu_ immediately without any problem.
- However the arrival of initial jobs posted by _.enqueue_ in and _.enqueue_at_ delays sometime. (about 6 minutes in below example even if they have been set to 1 minutes of delay. 15 minutes in another occasion and sometimes we never observe scheduler activity at all). 
- After sometime scheduler.py throws _RuntimeError_ .
- Then it looks working to be as expected more or less.

I wonder if anyone encountered a similar issue or have idea on resolution?

I don't believe the issue is associated with redis since _rq worker --with-scheduler_ functions as expected.

I used worker script at https://python-rq.org/docs/scheduling/ as a reference

***The Code***
pdate.py
```python
from datetime import datetime


def print_date():
    dt = datetime.now()
    print(dt)
    return dt
```
producer.py
```python
from datetime import datetime, timedelta

from redis import Redis
from rq import Queue

from pdate import print_date

QUEUE_NAME = "example"

c = Redis("localhost", 6379)
queue = Queue(QUEUE_NAME, connection=c)


def enqueue():
    job = queue.enqueue(print_date)
    print(f"Job {job.id}, enqueued_at: {job.created_at}")


def enqueue_in():
    job = queue.enqueue_in(timedelta(minutes=1), print_date)
    print(f"Job {job.id}, enqueued_at: {job.created_at}")


def enqueue_at():
    job = queue.enqueue_at(datetime.now() + timedelta(minutes=1), print_date)
    print(f"Job {job.id}, enqueued_at: {job.created_at}")


def main():
    enqueue()
    enqueue_in()
    enqueue_at()


if __name__ == "__main__":
    main()
```
scheduler.py
```python
from rq import Connection, Worker


with Connection():
    qs = ["example"]
    w = Worker(qs)
    w.work(with_scheduler=True)
```

***Stdout Log***
```zsh
(venv) fehim@Fehim lc-scheduling % python scheduler.py
16:04:13 Worker rq:worker:e960212124c84ddc827f5f1379d03d82: started, version 1.10.1
16:04:13 Subscribing to channel rq:pubsub:e960212124c84ddc827f5f1379d03d82
16:04:13 *** Listening on example...
16:04:13 Trying to acquire locks for example
16:04:13 Worker rq:worker:bacf8e46872844d9a46f1f60cbf4169d: started, version 1.10.1
16:04:13 Subscribing to channel rq:pubsub:bacf8e46872844d9a46f1f60cbf4169d
16:04:13 *** Listening on example...
16:04:13 Trying to acquire locks for example
16:04:26 example: pdate.print_date() (62c026a7-a5d7-4a36-94f1-1e2f224c19e0)
2022-05-03 16:04:26.176929
16:04:26 example: Job OK (62c026a7-a5d7-4a36-94f1-1e2f224c19e0)
16:04:26 Result is kept for 500 seconds

16:10:53 example: pdate.print_date() (82a2fa1e-b74a-4ee9-b7d7-09323a35cd20)
2022-05-03 16:10:53.035976
16:10:53 example: Job OK (82a2fa1e-b74a-4ee9-b7d7-09323a35cd20)
16:10:53 Result is kept for 500 seconds
16:14:38 example: pdate.print_date() (ab51f47c-bf62-4c01-84e8-9e5ff4091654)
2022-05-03 16:14:38.928646
16:14:38 example: Job OK (ab51f47c-bf62-4c01-84e8-9e5ff4091654)
16:14:38 Result is kept for 500 seconds
16:14:38 Trying to acquire locks for example
16:14:38 Worker rq:worker:bacf8e46872844d9a46f1f60cbf4169d: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/Users/fehim/Desktop/stash/lc-scheduling/venv/lib/python3.8/site-packages/rq/worker.py", line 591, in work
    self.run_maintenance_tasks()
  File "/Users/fehim/Desktop/stash/lc-scheduling/venv/lib/python3.8/site-packages/rq/worker.py", line 527, in run_maintenance_tasks
    self.scheduler.acquire_locks(auto_start=True)
  File "/Users/fehim/Desktop/stash/lc-scheduling/venv/lib/python3.8/site-packages/rq/scheduler.py", line 121, in acquire_locks
    self.start()
  File "/Users/fehim/Desktop/stash/lc-scheduling/venv/lib/python3.8/site-packages/rq/scheduler.py", line 213, in start
    self._process.start()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
16:14:38 Unsubscribing from channel rq:pubsub:bacf8e46872844d9a46f1f60cbf4169d
16:14:38 Scheduler for example started with PID 5057
16:14:39 example: pdate.print_date() (5930fdc1-dbf3-409b-a30f-e0eba11c4630)
2022-05-03 16:14:39.016781
16:14:39 example: Job OK (5930fdc1-dbf3-409b-a30f-e0eba11c4630)
16:14:39 Result is kept for 500 seconds
16:14:39 Cleaning registries for queue: example
16:14:39 example: pdate.print_date() (a001148e-f069-4818-adec-374ee94a53e2)
2022-05-03 16:14:39.065857
16:14:39 example: Job OK (a001148e-f069-4818-adec-374ee94a53e2)
16:14:39 Result is kept for 500 seconds
16:14:39 example: pdate.print_date() (ae1e4608-1258-404a-b927-8ec37de1ba9f)
2022-05-03 16:14:39.104830
16:14:39 example: Job OK (ae1e4608-1258-404a-b927-8ec37de1ba9f)
16:14:39 Result is kept for 500 seconds
16:14:39 example: pdate.print_date() (fec313b9-3ab0-45df-bb56-d18517f71211)
2022-05-03 16:14:39.146296
16:14:39 example: Job OK (fec313b9-3ab0-45df-bb56-d18517f71211)
16:14:39 Result is kept for 500 seconds
16:14:39 example: pdate.print_date() (7d7a9c3b-699f-4965-8a80-dd12335a64d8)
2022-05-03 16:14:39.185533
16:14:39 example: Job OK (7d7a9c3b-699f-4965-8a80-dd12335a64d8)
16:14:39 Result is kept for 500 seconds
16:14:39 example: pdate.print_date() (edfade21-ada4-4519-86a4-14f395d923c8)
2022-05-03 16:14:39.227899
16:14:39 example: Job OK (edfade21-ada4-4519-86a4-14f395d923c8)
16:14:39 Result is kept for 500 seconds
16:15:38 example: pdate.print_date() (2a9f0b37-806d-45d1-a5cc-5d0fb537af77)
2022-05-03 16:15:38.698103
16:15:38 example: Job OK (2a9f0b37-806d-45d1-a5cc-5d0fb537af77)
16:15:38 Result is kept for 500 seconds
16:15:38 example: pdate.print_date() (3b999931-1edd-4893-824c-25b824d3a30f)
2022-05-03 16:15:38.736348
16:15:38 example: Job OK (3b999931-1edd-4893-824c-25b824d3a30f)
16:15:38 Result is kept for 500 seconds
```
```zsh
(venv) fehim@Fehim lc-scheduling % python producer.py  
Job 626430b2-8195-4188-b900-b672e5eb8741, enqueued_at: 2022-05-03 12:53:18.057592
Job 673179d8-ad9b-4694-b855-01ce99165725, enqueued_at: 2022-05-03 12:53:18.067724
Job 5a3b85a4-bdc1-425d-b449-d2c1abccfce4, enqueued_at: 2022-05-03 12:53:18.071804
(venv) fehim@Fehim lc-scheduling % python producer.py
Job 707e64c8-314d-4fa5-822d-0d461d0ccb6c, enqueued_at: 2022-05-03 13:03:20.779921
Job 5930fdc1-dbf3-409b-a30f-e0eba11c4630, enqueued_at: 2022-05-03 13:03:20.791316
Job a001148e-f069-4818-adec-374ee94a53e2, enqueued_at: 2022-05-03 13:03:20.796513
(venv) fehim@Fehim lc-scheduling % python producer.py
Job 62c026a7-a5d7-4a36-94f1-1e2f224c19e0, enqueued_at: 2022-05-03 13:04:26.145851
Job fec313b9-3ab0-45df-bb56-d18517f71211, enqueued_at: 2022-05-03 13:04:26.156054
Job ae1e4608-1258-404a-b927-8ec37de1ba9f, enqueued_at: 2022-05-03 13:04:26.160580
```
***Expected Behaviour***

Expecting to see a healthy start, similar to built-in CLI script:

```zsh
(venv) fehim@Fehim lc-scheduling % rq worker --with-scheduler example
16:33:14 Worker rq:worker:7e28f6eeabd6406aa2c8dd36e1d9ee09: started, version 1.10.1
16:33:14 Subscribing to channel rq:pubsub:7e28f6eeabd6406aa2c8dd36e1d9ee09
16:33:14 *** Listening on example...
16:33:14 Trying to acquire locks for example
16:33:14 Cleaning registries for queue: example
16:33:29 example: pdate.print_date() (17e7a4cf-6b92-4f07-afe3-d1a64eaa45c8)
2022-05-03 16:33:29.820019
16:33:29 example: Job OK (17e7a4cf-6b92-4f07-afe3-d1a64eaa45c8)
16:33:29 Result is kept for 500 seconds
16:34:29 example: pdate.print_date() (c882e8d2-ed0d-4450-be40-074e205a3346)
2022-05-03 16:34:29.977199
16:34:29 example: Job OK (c882e8d2-ed0d-4450-be40-074e205a3346)
16:34:29 Result is kept for 500 seconds
16:34:30 example: pdate.print_date() (de35f401-e84f-471d-bdbb-e36f22a85fad)
2022-05-03 16:34:30.023180
16:34:30 example: Job OK (de35f401-e84f-471d-bdbb-e36f22a85fad)
16:34:30 Result is kept for 500 seconds
```

***Setup***
- Python:
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

- RQ:
  - rq==1.10.1
  - rq-scheduler==0.11.0
  - aioredis==2.0.0
  - hiredis==2.0.0
  - redis==4.2.2
  - click==8.1.2

- Redis: redis:7.0.0 image on Docker

***Steps To Reproduce***

```zsh
python scheduler.py
```
```zsh
python producer.py  
python producer.py
python producer.py
```

**Comment by selwin** [comment] 2022-07-24 00:09
This is not a bug or feature request about RQ itself so I'm closing this issue.

**Closed by selwin** 2022-07-24 00:09 UTC
