### ISSUE TITLE
Retrying failed tasks doesn't work when a rqworker goes down

### ISSUE THREAD

**Issue by lcosmin** [rq/rq#1758] opened 2023-01-19 10:30 UTC
Running rq version 1.12.0.

I have a setup consisting of two `rqworker`s (running with `--with-scheduler`) on two sepparated machines and a task that fails constantly by raising an exception (for testing purposes). 

I enqueue the task using `enqueue_call(my_task, args=(arg1, arg2), retry=Retry(max=60, interval=10))`.

Watching the logs on both machines, I notice the task being executed, the exception raised, re-executed after the specified interval and so on. All seems to be working properly and **both** `rqworker`s can pick up the task to run it. 

However, if I shut down the worker **that first picked up** the task (ctrl-c), it seems that the task doesn't get executed by the second worker anymore. 

It's like the first worker coordinates the execution of the retry and once it's gone, so is the task. Of course, after I start it back up, the execution resumes. I would expect the second worker to continue running it. 

So, I wonder, is this the expected/desired behavior? Because in a cloud environment (where machines get downscaled from time to time) this would lead to losing tasks (if the "coordinator" goes down).

**Comment by lowercase00** [comment] 2023-01-20 22:26
@lcosmin just to make sure I can replicate this, you're stopping the worker (1) after the first exception right?

As far as I understand, the job (and the retry) shouldn't be attached to a worker, but rather to a queue, if both workers are listening to the same queue I guess they should be able to handle this situation. 

I'll double check and try to replicate this.

**Comment by lowercase00** [comment] 2023-01-21 03:02
@lcosmin I couldn't reproduce this. My current setup:

```python
# local/app.py
from redis import Redis
from rq import Queue, Retry
q = Queue(connection=Redis())
q.enqueue("local.task.mytask", retry=Retry(max=5))
```

```python
# local/task.py
import time
def mytask():
    time.sleep(2)
    raise Exception("This is an error")
```

Spin up two workers. Run app.py. After the Worker 1 get's the task and raises the exception, stop the worker with `ctrl + c` , worker two still gets the second task. Perhaps you're running workers without `--with-scheduler`? This is required when you are using `interval`.

> If you use `interval` argument with `Retry`, don't forget to run your workers using the `--with-scheduler` argument.

Feel free to add more details to reproduce this.

**Comment by lcosmin** [comment] 2023-01-21 10:11
I've managed to reproduce it locally using your example as a starting point. I did a slight variation so that the example matches my real world use case (i.e. use `enqueue_call` and have some arguments), but it seems the thing that triggers the behavior is using `interval=XX` as an argument for `Retry`. 

My code:

```python
# local/enqueue.py
from redis import Redis
from rq import Queue, Retry

q = Queue(connection=Redis())
q.enqueue_call("local.task.mytask", args=(1, 2), retry=Retry(max=5, interval=5))
```

```python
import time
def mytask(a, b):
    time.sleep(2)
    print(f"a={a}, b={b}")
    raise Exception("This is an error")
```

Here's an [asciinema](https://asciinema.org/a/f3PT0MfruuF3Njrij61DLGLwE) of the issue.

I also noticed that the two workers don't issue the same start up message, one is missing the message about starting the scheduler despite being run with --with-scheduler.  

Let me know if this helps you reproduce it.

**Comment by lowercase00** [comment] 2023-01-21 12:05
You're right, I left the `interval` out, but that's exactly what's causing it.
So my first guest here is that this is related to the `lock` mechanism for the scheduler, which exists to prevent multiple schedulers picking up the same tasks. The worker does release the lock (as it shows on the logs when you kill it), the other worker will them try to acquire the lock, but will do so only after X amount of time, I think this is the logic where this is defined:

```python
    @property
    def should_reacquire_locks(self):
        """Returns True if lock_acquisition_time is longer than 10 minutes ago"""
        if self._queue_names == self.acquired_locks:
            return False
        if not self.lock_acquisition_time:
            return True
        return (datetime.now() - self.lock_acquisition_time).total_seconds() > 600
```

Can you try waiting for those 10 minutes to see if it picks up the lock again?
Or you can maybe run your own copy reducing the `600` to something very small.

I think there are a couple of things that might be improved here:
- Heaving the `600` to be a parameter for the worker (`fallback_interval`)
- Potentially reducing the default value (I'm not sure what was the history behind that choice, so there might be other reasons this value was used)
- On the `stop` logic, if it has the lock acquired, erases the `lock_acquisition_time` attribute, that should allow for the next worker to acquire the lock, since this is the first attribute that is checked while a worker decides whether it should (or should not) acquire the lock. More tests would be needed in a case where there are multiple worker instances though, not sure if that would work in a scenario with multiple (like 10) workers.

I wonder if adding this would work:

```python
    def release_locks(self):
        """Release acquired locks"""
        keys = [self.get_locking_key(name) for name in self._queue_names]
        self.connection.delete(*keys)
        self._acquired_locks = set() 
        self.lock_acquisition_time = None # This
```

**Comment by lcosmin** [comment] 2023-01-21 16:12
Indeed, the other worker seems to pick up the task after a while (more than 10 minutes).

```^C17:38:55 Warm shut down requested    ```  <--- first worker stopped at 17:38

Second worker picks up the task:

```
17:52:14 Cleaning registries for queue: default 
17:52:14 Scheduler for default started with PID 9995   
17:52:14 default: local.task.mytask(1, 2) (2c3eaa87-4693-49f1-b443-e09c3d1d22dc)
```

It would make sense for the first worker to clean up any locks, and it could do that since I'm gracefully shutting it down (via `SIGINT` instead of `SIGKILL`)

**Comment by lowercase00** [comment] 2023-01-21 17:24
@selwin do you see any downside on clearing the `lock_acquisition_time` when the scheduler is killed, and moving the `fallback_interval` to be a parameter of the scheduler?

**Comment by lowercase00** [comment] 2023-01-27 02:44
New fallback period is now 2 minutes. Unfortunately this can't be configured for now, we might review that when looking at other forms of configuration. I'm closing this as it's not actually an issue, but rather a behavior.

**Closed by lowercase00** 2023-01-27 02:44 UTC
