### ISSUE TITLE
Programmatically create more workers at run-time

### ISSUE THREAD

**Issue by sivabudh** [rq/rq#689] opened 2016-04-07 13:01 UTC
Is there a way to programmatically create more workers at run-time? When the work finishes the job, it simply dies. In this way, I can minimize the amount of jobs waiting in the queue.

**Comment by shivekkhurana** [comment] 2016-08-23 06:54
Yes you can. But because you want the worker to die, you'll have to start 
 - an all-time running worker using the `rq worker` command and 
 - on demand workers by saving the following code in some file, say `on_demand_workers.py` and then calling `$ python on_demand_workers.py`

Both of the command should ideally be run under a task monitor (supervisor or circus)

```python
#!/usr/bin/python3

import sys
import time
from rq import Connection, Worker
from redis import Redis

redis = Redis(host='localhost')

def need_burst_workers():
    # check database or redis key to determine whether burst worker army is required
    return True #boolean

def num_burst_workers_needed():
    # check the number, maybe divide the number of pending tasks by n
    return 10 #integer

def main(qs):
    with Connection(connection=redis):
        if need_burst_workers():
            [Worker(qs).work(burst=True) for i in range(num_burst_workers_needed())]
        else:
            time.sleep(10) #in seconds

if __name__ == '__main__':
    qs = sys.argv[1:] or ['default']
    main(qs)
```

Hope this helps. Thank you.

**Comment by proofit404** [comment] 2016-08-23 07:42
Worker.work is blocking call. This code creates ten workers sequentially. Wrap work method call into multiprocessing at least.

**Comment by shivekkhurana** [comment] 2016-08-23 08:56
@proofit404 : I didn't realize this while answering. Thanks for pointing this out.

The updated `__name__ == '__main__'` block  is  : 

```python
import multiprocessing
import subprocess 

def main(qs):
    with Connection(connection=redis):
        if need_burst_workers():
            [Process(target=Worker(qs).work, kwargs={'burst': True}).start() for i in range(num_burst_workers_needed())]
        else:
            time.sleep(10) #in seconds
````

Source: ![http://stackoverflow.com/questions/18864859/python-executing-multiple-functions-simultaneously](http://stackoverflow.com/questions/18864859/python-executing-multiple-functions-simultaneously)

**Comment by proofit404** [comment] 2016-08-23 09:08
@shivekkhurana looks correct.

I prefer to use for loops to perform actions (like process creation) and list comprehensions for data structures.  So for this case I suggest you to use for loop.

**Comment by ronnielivingsince1994** [comment] 2019-06-20 07:56
This looks pretty neat!

However, I'm facing a constraint on the number of workers. I can't create a large number of worker force.

Is their a way to create child processes for each worker?

**Comment by ronnielivingsince1994** [comment] 2019-06-20 10:51
Or can there be multiple workers on one connection?!

**Comment by evanphilipsmith** [comment] 2022-04-17 06:04
> ```python
> import multiprocessing
> 
> def main(qs):
>     with Connection(connection=redis):
>         if need_burst_workers():
>             for i in range(num_burst_workers_needed()):
>                 multiprocessing.Process(target=Worker(qs).work, kwargs={'burst': True}).start()
>         else:
>             time.sleep(10) #in seconds
> ```

When I run this code snippet in Python 3.10, I get the following error:
```
TypeError: cannot pickle '_thread.lock' object
```
I believe this is because of limitations in `pickle` in newer versions of Python (https://github.com/rq/rq/issues/1413#issuecomment-785014951). What is the latest way to programmatically create more workers using `multiprocessing`?

**Comment by evanphilipsmith** [comment] 2022-05-12 20:42
In case it helps someone else down the road, here's how I've been able to programmatically create more workers with `multiprocessing` in Python 3.10.

```python
import multiprocessing

def start_worker(queues):
    from rq import Connection, Worker

    with Connection():
        worker = Worker(queues)
        worker.work()

def main(queues):
    multiprocessing.Process(target=start_worker, args=(queues,)).start()
```

Alternatively, I've figured out a hacky way to make a `Redis` instance pickleable by creating a wrapper class that stores the metadata used to instantiate `Redis`, and deletes/reinitializes it when it is pickled/unpickled.
```python
from redis import Redis

class PickleableRedis:
    def __init__(self, **kwargs):
        self.redis = Redis(**kwargs)
        self.redis_kwargs = kwargs

    def __getattr__(self, name):
        # Exposes the Redis API
        return getattr(self.redis, name)

    def __getstate__(self):
        # Called when pickled
        state = self.__dict__.copy()
        state['redis'] = None
        return state

    def __setstate__(self, state):
        # Called when unpickled
        self.__dict__.update(state)
        self.redis = Redis(**self.redis_kwargs)
```

**Comment by lowercase00** [comment] 2023-01-27 01:28
This is a won't fix: it can be done manually (couple of examples in here), or be organized with an orchestrator (eg. K8S).

**Closed by lowercase00** 2023-01-27 01:28 UTC

**Comment by mechaadi** [comment] 2023-02-13 07:34
For anyone who needs to start the rqworker from a python script and getting this error - 

```
 An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

The issue is that a thread needs to be created from the main process/module [read more](https://docs.python.org/3/library/__main__.html).
This might help - 

```
def start_worker(queues):
    from rq import Connection, Worker

    with Connection(connection=redis):
        worker = Worker(queues)
        worker. Work()

if __name__ == "__main__":
    for i in range(num_burst_workers_needed()):
        multiprocessing.Process(target=start_worker, args=(queues)).start()
```
