### ISSUE TITLE
Worker configuration import in rqworker getting error on python 2.7.6

### ISSUE THREAD

**Issue by howonlee** [rq/rq#567] opened 2015-07-30 18:02 UTC
I know there were a bunch of changes in the transition from 2 to 3 of how dynamic importing works, so I think that this is one of those things.

I have rq worker configs in a file, pass it to rqworker and it looks like the cli is dynamically trying to import them by passing the path to `__import__`, and failing like so:

```
Traceback (most recent call last):
  File "/home/hlee/Envs/constructor/bin/rqworker", line 11, in <module>
    sys.exit(worker())
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/rq/cli/cli.py", line 154, in worker
    settings = read_config_file(config) if config else {}
  File "/home/hlee/Envs/constructor/local/lib/python2.7/site-packages/rq/cli/helpers.py", line 23, in read_config_file
    settings = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Import by filename is not supported.
```

And indeed, this is not how `__import__` is supposed to work, I believe. [There is a bit in the python docs](https://docs.python.org/2/whatsnew/2.6.html#porting-to-python-2-6)

There's a [stack post](http://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path) about it. You could use one of those methods or I could give you a PR

**Comment by selwin** [comment] 2015-08-12 02:08
I personally don't know too much about this because I don't use a configuration file, but it would be awesome you could create a PR. Please attach a test along with it because I don't want to accidentally break other people's scripts ;)

**Comment by howonlee** [comment] 2015-08-12 03:17
will do

**Comment by chriscohoat** [comment] 2015-09-05 01:27
Hey guys, stumbled upon this issue as well today. While it doesn't happen in my local OSX environment it does consistently happen in a dockerized Ubuntu 14.04 w/ Python 2.7.6 environment. 

Let me know if there's anything I can help with from a pull request perspective.

**Comment by selwin** [comment] 2015-09-05 02:22
It would be great if you can identify what the problem is and open a PR :)

**Comment by ivo5307** [comment] 2016-03-01 19:24
Same as @chriscohoat  OSX works, Ubuntu 14.04 w/ P 2.7.6 no.
Seems still no PR?

**Comment by selwin** [comment] 2019-09-08 12:14
Closing this issue. Please reopen if there's any new details.

**Closed by selwin** 2019-09-08 12:14 UTC
