### ISSUE TITLE
Jobs that timeout don't have job.ended_at set

### ISSUE THREAD

**Issue by selwin** [rq/rq#1225] opened 2020-03-31 10:17 UTC

**Comment by pranavgupta1234** [comment] 2020-07-07 14:07
Hi @selwin ,

Is this still an issue ? Because I tried with jobs that timeout and their job.ended_at was set. Let me know how to reproduce it, if its reproducible.

**Comment by lowercase00** [comment] 2023-01-28 04:42
Closing, feel free to reopen if this is still an issue.

**Closed by lowercase00** 2023-01-28 04:42 UTC
