### ISSUE TITLE
ResponseError: Command # 7 (EXPIRE rq:worker:durip2.22880 None) of pipeline caused error: value is not an integer or out of range

### ISSUE THREAD

**Issue by smsaladi** [rq/rq#961] opened 2018-06-02 21:39 UTC
I'm facing the following issue when launching rq workers. Would someone be able to suggest steps to troubleshoot? Although I've used rq for a while, I'm rather unfamiliar with the backend and would appreciate any input.

```text
(base) ➜  jetfighter git:(master) ✗ FLASK_APP=webapp.py flask rq worker
Traceback (most recent call last):
  File "/home/saladi/anaconda3/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/flask_rq2/cli.py", line 53, in new_func
    return func(rq, ctx, *args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/flask_rq2/cli.py", line 151, in worker
    **shared_options(rq)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/rq/cli/cli.py", line 75, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/rq/cli/cli.py", line 236, in worker
    worker.work(burst=burst, logging_level=logging_level)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/rq/worker.py", line 466, in work
    self.register_birth()
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/rq/worker.py", line 289, in register_birth
    p.execute()
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/redis/client.py", line 2879, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/redis/client.py", line 2794, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/home/saladi/anaconda3/lib/python3.6/site-packages/redis/client.py", line 2828, in raise_first_error
    raise r
redis.exceptions.ResponseError: Command # 7 (EXPIRE rq:worker:durip2.22880 None) of pipeline caused error: value is not an integer or out of range
```

**Comment by smsaladi** [comment] 2018-06-02 21:41
I am running the following on ubuntu 16.04:
rq, version 0.11.0

✗ redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=30b097ce55e345e5

Flask 0.12.2
Python 3.6.4 |Anaconda custom (64-bit)| (default, Mar 13 2018, 01:15:57)
[GCC 7.2.0]

flask-rq-0.2

**Comment by selwin** [comment] 2018-06-03 23:56
@smsaladi can you downgrade to RQ 0.11 and see if this error still happens?

**Comment by smsaladi** [comment] 2018-06-04 00:02
@selwin thanks for the suggestion Do you mean RQ 0.10.0?

**Comment by smsaladi** [comment] 2018-06-04 00:04
Sorry for the spam, looks like downgrading to 0.10.0 fixed it:

(base) ➜  ~ pip install rq==0.10.0
Collecting rq==0.10.0
  Downloading https://files.pythonhosted.org/packages/c3/3d/77bc4f7fa96910c7abf99206be2eb9aefa6a0e33d622349a96e633a1548e/rq-0.10.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 9.3MB/s
Requirement already satisfied: click>=5.0 in ./anaconda3/lib/python3.6/site-packages (from rq==0.10.0) (6.7)
Requirement already satisfied: redis>=2.7.0 in ./anaconda3/lib/python3.6/site-packages (from rq==0.10.0) (2.10.6)
Installing collected packages: rq
  Found existing installation: rq 0.11.0
    Uninstalling rq-0.11.0:
      Successfully uninstalled rq-0.11.0
Successfully installed rq-0.10.0
(base) ➜  ~ cd github
(base) ➜  github cd jetfighter
(base) ➜  jetfighter git:(master) ✗ FLASK_APP=webapp.py flask rq worker
17:03:25 RQ worker 'rq:worker:durip2.11695' started, version 0.10.0
17:03:25 *** Listening on default...
17:03:25 Cleaning registries for queue: default
17:03:25 default: webapp.process_paper(<Biorxiv (transient 139764604962912)>) (a11ad8ca-5a9a-48a0-9955-169c823a25e3)
entered job

**Comment by smsaladi** [comment] 2018-06-04 00:04
@selwin Let me know if I can give you other details that would help debug

**Comment by selwin** [comment] 2018-06-04 00:16
This change is probably the cause: https://github.com/rq/rq/pull/945/commits/544ca0ffe729f70e0936bc41112c5c872177d3c6#diff-1aac421e8c53e895ee40f3b7dc63144fL182

we moved the `default_worker_ttl` default value assignment to https://github.com/rq/rq/pull/945/commits/544ca0ffe729f70e0936bc41112c5c872177d3c6#diff-1aac421e8c53e895ee40f3b7dc63144fR158

I'm assuming somewhere in your code you're instantiating `worker` with `Worker(default_worker_ttl=None)` which is no longer valid in RQ 0.11 . Could you please confirm whether this is the case?

**Comment by smsaladi** [comment] 2018-06-04 00:28
Actually, I think this has already been brought up here! https://github.com/rq/Flask-RQ2/issues/61

**Comment by jezdez** [comment] 2018-09-19 09:09
FWIW this has been fixed downstream in Flask-RQ2.

**Comment by selwin** [comment] 2018-09-23 13:43
Marking this as fixed.

**Closed by selwin** 2018-09-23 13:43 UTC
